name: Android CI (Debug APK - subdir)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Install build tools & platforms
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.9

    - name: Build Debug APK
      working-directory: nepisireyim
      run: gradle assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: nepisireyim-debug-apk
        path: nepisireyim/app/build/outputs/apk/debug/app-debug.apk
